### ISSUE TITLE
Hypixelでのログインメッセージ

### ISSUE THREAD

**Issue by ghost** [SimplyRin/SimpleNickMod#1]
Hypixelでログインしたときに表示される○○ joined.のjoined.の部分に○○の部分のカラーコードが反映されてしまいます。
![4fc0c60a09c176c74a98a2e058b60ac2](https://user-images.githubusercontent.com/26434739/28822597-ceee09a8-76f4-11e7-8263-a6e8d8b863b3.png)

**Comment by SimplyRin** [comment]
ご報告ありがとうございます。
問題を修正し新しいバージョンをリリースしました！
